### ISSUE TITLE
Hoverboard v2 Roadmap

### ISSUE THREAD

**Issue by jesseskinner** [jesseskinner/hoverboard#12]
After a few months in use I have some ideas of the next version of the API. Here are some of my goals and thoughts, not set in stone. **Please, let me know your thoughts on any of this.**

- ~~Allow Hoverboard to be used as a base class (extended) with ECMAScript 6 classes.~~
- Stop being clever about renaming methods (action vs. onAction) and instead consider all public methods as actions.
- Allow passing initial state into constructor for "rehydration" of models created on server side.
- Eliminate `getInitialState` and just use a constructor, rehydration, or override `getState` instead.
- Consider alternative names for `this.state`, `getState` and `setState`, but probably will keep them.
- ~~Figure out what all of this looks like on ES5 as well.~~
- If too much friction or confusion, I might just launch this as a new, separate project with a different name.

Here's a possible example of usage in v2:

```javascript
class MyModel extends Hoverboard {
    constructor(state) {
        super(state);

        // start loading async data immediately
        setTimeout(() => this.addItem('async'), 1000);
    }

    setState(data) {
        // do processing on any data passed through here (eg. add meta data, filter)
        data.listLength = data.list ? list.length : 0;

        return super.setState(data);
    }

    getState(callback) {
        // could start lazily loading async data here
        api.get('list/pages/count').then((pageCount) => this.setState({ pageCount });

        return super.getState(callback);
    }

    // note this is an action and it's not called onAddItem
    addItem(item) {
        var list = this.state.list || [];
        list.push(item);

        this.setState({ list: list });
    }
}

// create instance of model and pass in initial state
var model = new MyModel({ list: ['one', 'two'] });

// add a listener
var unsubscribe = model.getState(function (state) {
    // do stuff with state
});

// call an action
model.addItem('new item');
```

**Comment by jesseskinner** [comment]
After reading this article, I'm rethinking making Hoverboard an ES6 class.

https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a

**Comment by jesseskinner** [comment]
Redux (https://github.com/gaearon/redux) is very cool too, wondering if Hoverboard v2 could adopt or incorporate  the more functional and stateless approach of Redux reducers.

**Comment by prabirshrestha** [comment]
+1 for pure function. was about to recommend redux style pure functions few days back. Always good to have different options.

**Comment by jesseskinner** [comment]
So maybe actions in Hoverboard could be implemented as Redux-style stateless reducers, eliminating the needs for `this.state`, `this.getState` and `this.setState` altogether. All actions could be stateless and not *need* `this` for anything (but could still use it internally as desired).

Actually, `getInitialState` could also be replaced with an action that triggers loading. And the actions object could also be a function that replaces `model.getState`. If we do these things, we approach almost zero API. No function names to memorize!

Unlike Redux, Hoverboard could still take responsibility for merging in resulting state into the current state object.

```javascript
var MyModel = {
    // an action's signature could now be (state, ...args) => state
    addItem(state, item) {
        var list = state.list || [];
        list.push(item);
        return { list };
    }

    // action resolution could also be async by returning a function that'll be passed a callback
    loadItems(state) {
        return setState => {
            // alter the state early with the loading status
            setState({ isLoading: true, error: null });

            // alter the state again when data loads or fails
            api.get('items').then(
                result => setState({ isLoading: false, list: result }),
                error => setState({ isLoading: false, error: error })
            );
        }
    }
};

// create instance of model and pass in initial state (note - this doesn't work yet)
var model = Hoverboard(MyModel, { list: ['one', 'two'] });

// trigger loading of items
model.loadItems();

// add a listener. maybe model itself could be a function that takes a callback?
var unsubscribe = model(function (state) {
    // do stuff with state
});

// call action - note we don't pass in state, it will be done automatically/internally
model.addItem('something');
```

This way, a test suite could easily test MyModel.addItem(state, item) without involving Hoverboard at all.

**Comment by jesseskinner** [comment]
Glad you agree @prabirshrestha, and not just because you're apparently the only user of Hoverboard ;)

Very interested what you think of the potential new syntax.

**Comment by prabirshrestha** [comment]
I have been trying bunch of flux and currently use redux but use hoverboard for small apps :)

Here are some of the features I would like a flux library to support.

* Pure Functions like redux. Makes it to easy write unit tests, reason about
* Hot reload
* Dynamically load stores (similar to nuclear js) and unload it (or at least set the state value to null/undefined so the gc can run).
* serialize/deserialize stores for rehydration.
* allow to set the initial store set when dynamically loading.
* Getters similar to NuclearJS/Hoverboard.
* Better TypeScript support. Hoverboard v1 is bad at this since it uses `on` Prefix. Also don't like the redux switch case. Coz I can't guarantee the payload to be of the type related to the action type. I can easily make a mistake here in `Action<AddProduct>>` and use `<Action<RemoveProduct>` instead.
```typescript
export function products(state = []: Products[], action: any) { // here the action is any
    switch (action.type) {
        case 'ADD_PRODUCTS':
           return [...state, (<Action<AddProduct>>action).products];   // here action has products.
       case 'REMOVE_PRODCUTS':
           return .... (<Action<RemoveProduct>>action)action.productId;//  here action has productId
    }
}
```
This does mean no constants and store will be coupled with action but that might be a good thing not sure. Need to play around with it. If I'm using JS i'm fine with constants. This could be solved by using https://github.com/gaearon/redux#but-there-are-switch-statements so might not be a huge problem for JS folks.

* Easily test components
* support for context as mentioned in https://github.com/jesseskinner/hoverboard/issues/10
* Debugger tool. (Right click the store state and generate unit tests?)
* time travel
* don't force to use immutable.js but allow me to use it easily like redux
* (future. some interesting to think about) remote stores. For example save the actual data in SharedWorker and use getter to project partial store in the actual browser window. Allows to reuse in different browser tabs.

**Comment by prabirshrestha** [comment]
I would prefer plain functions over object.

```js
var MyModel = {
    addItem(state, item) {

    }

    loadItems(state) {

    }
};
```

The above could be easily written as

```js
export function addItem(state, item) {
    
}

export function loadItems(state) {
    
}
```

```js
import * as MyModel from './MyModel';
```

I think having actions and state separate is better although it means more code. I found it is more explicit and easier to test.

```js
export function addTodo(text) {
    return {
        type: 'ADD_TODO',
        payload: text
    };
}

export class Button extends React.Component {
    handleClick(e) {
        e.preventDefault();
        var text = React.findDOMNode(this.refs.todo).textContent;
        this.context.dispatch(addTodo(text));
    }
    render() {
        return <form>
            <input type="text" ref="todo" />
            <button onClick={this.handleClick}>Add Todo</button>;
        </form>;
    }
}
```

This allows me to test the component without implementing the store. The only test I would need to write here is the text in `addTodo` is the same as the input value.

But now this doesn't look like hoverboard at all.

**Comment by jesseskinner** [comment]
What you've outlined is different from my examples but I think still possible. Hoverboard at its core is just an action dispatcher and state change listener. So with the separate action and dispatcher, you could do something like this:

```javascript
var TodoStore = Hoverboard({
  addTodo: function (state, text) {
    return { list: [ ...state.list, text ] };
  } 
});

// translate action objects to Hoverboard actions
function dispatch(action) {
  switch (action.type) {
    case 'ADD_TODO':
      return TodoStore.addTodo(action.payload);
  }
}

TodoStore(function (state) {
   // pass changes along to component
});
```

I revamped Hoverboard last night, so the master branch is basically v2.0.0-rc1, if you want to try it out or have a look.

**Comment by prabirshrestha** [comment]
But how do I not use singleton. `TodoStore.addTodo(action.payload)`. I want to use context. How do I solve this problem? https://github.com/jesseskinner/hoverboard/issues/10

**Comment by jesseskinner** [comment]
@prabirshrestha I'll work on that and get back to you :)

**Comment by jesseskinner** [comment]
Ok, after mulling this over for a few months I think I will simplify things even more and remove the ability to use setState in any context, including removing the initialization function. In other words, there would only be actions, which should themselves be pure functions. Anything async would have to go back through those same actions. Initial state can also be done through an "init" or "reset" action. This will lead to a very simple and minimal API without losing functionality.

Async data could be done like this:

```javascript
var Store = Hoverboard({
    data: function(state, error, data) {
        return { isLoading: false, error: error, data: data };
    },
    
    load: function (state, params) {
        getDataFromAPI(params, function(error, data){
            Store.data(error, data);
        });

        return { isLoading: true };
    };
});
```

The ClickCounter example could be done like this:

```javascript
var ClickCounter = Hoverboard({
    click: function (state, text) {
        return {
            value: state.value + 1,
            log: state.log.concat(text)
        };
    },
    reset: function () {
        // return initial state
        return {
            value: 0,
            log: []
        };
    }
});

// set to initial state
ClickCounter.reset();

// listen to changes to the state
var unsubscribe = ClickCounter(function (clickState) {
    document.write(JSON.stringify(clickState) + "<br>");
});

ClickCounter.click('first');
ClickCounter.click('second');

// re-initialize back to empty state
ClickCounter.reset();

unsubscribe();

ClickCounter.click("This won't show up");
```

**Comment by prabirshrestha** [comment]
Seems like your actions are just a reducer. I was just playing with this after seeing this example today https://gist.github.com/newtriks/a223b80baa3dd8765713

Here is the sample I have been playing with: http://jsbin.com/wunezi/6/edit?html,js,output

Actions are basically just a reducer that returns new state. use dispatch to perform the action.

Inline the code here from the jsbin.

```js
var initialState = {
  counter: 0
};

var actionsStream = new Rx.Subject();
var store = Rx.Observable.merge(actionsStream)
  .scan((state, reduce) => reduce(state), initialState);
var dispatch = reduce => actionsStream.onNext(reduce);
  
var update = React.addons.update;

var increment = n => state => update(state, {
  counter: { $set: state.counter + n }
});

var decrement = n => state => update(state, {
  counter: { $set: state.counter - 1}
});

var App = React.createClass({
  
  render() {
    return <div>
      <button onClick={this._handleIncrement}>Increment</button>
      <button onClick={this._handleDecrement}>Decrement</button>
      {this.props.counter}
    </div>;
  },
  
  _handleIncrement(e) {
    e.preventDefault();
    this.props.dispatch(increment(1));
  },
  
  _handleDecrement(e) {
    e.preventDefault();
    this.props.dispatch(decrement(1));
  }
  
});

store.subscribe(state => React.render(<App dispatch={dispatch} {...state} />, document.getElementById('app')));
dispatch(state => state);
```

**Comment by jesseskinner** [comment]
@prabirshrestha Yes, the new actions are only pure reducer functions. What Hoverboard provides additionally is: remembering the resulting state, passing it along via pub/sub, and merging in the result from each action/reducer function. So in that sense these aren't Array.reduce reducers, because what you return from them is shallow-merged into the store's state, which is a small convenience so you don't have to use merge functions or spread operators yourself.

That's a neat concept you included. So instead of calling a function to trigger an action, you dispatch a reducer function which applies to the data. So you're basically creating a function which can mutate the data and passing it along to the store to apply it to the data. The downside is that it might be harder to log or track the actions, and it will allow developers to pass arbitrary actions (or maybe that's an upside in some cases).

**Comment by jesseskinner** [comment]
Hoverboard v2.0.0 has been released. I've also updated the Hoverboard TodoMVC example. Looking forward to any feedback, questions or possible issues people run into.
