### ISSUE TITLE
Complex Async Scenarios..

### ISSUE THREAD

**Issue by mikecann** [jesseskinner/hoverboard#22]
Hi,

Apologies for so many tickets.

This one is kind of tricky to explain.

Suppose I have an AppStore which has state { isInitted: boolean } and an "init" action.

For app store to be considered initted it must tell the AuthStore to init itself (an async operation) if that operation completes then the UserStore needs to load (async) the user based on the token that the AuthStore loaded from localStorage. 

So you have a chain of async operations going on there. Normally you could handle this with promises or async await no problem but with stores its different as they dont return promises. 

How would you recommend solving this chained async problem? 

Mike

**Comment by jesseskinner** [comment]
I enjoy the tickets, file as many as you want.

I try to keep my actions synchronous and keep asynchronous activity outside of the store like this:

```javascript
const AppStore = Hoverboard({
  init: (state, token) => ({ token })
}, { token: null })

api('user/token').then(token => AppStore.init(token))

const UserStore = Hoverboard({
  init: (state, userData) => userData
})

AppStore(({ token }) => {
  // when the token arrives, if we haven't already initialised UserStore, fetch user data
  if (token && !UserStore()) {
    api.get('user/data').then(userData => UserStore.init(userdata))
  }
})
```

There are lots of ways to do it - and it's up to you how you want to organize the above into functions, files & modules.

**Comment by mikecann** [comment]
Hi,

Good to know im not bugging you too much.

I thought about your suggested implementation and thats what I was going to do but I was worried about "callback confusion". 

This is going to get a little abstract so I do apologise if it doesnt make sense...

By that I mean by "callbak confusion" that if you handling async logic with callbacks:

```
AppStore(({ token }) => {
  // when the token arrives, if we haven't already initialised UserStore, fetch user data
  if (token && !UserStore()) {
    api.get('user/data').then(userData => UserStore.init(userdata))
  }
})
```

The problem is that in some instances you may not want that specific logic to occur. For example perhaps some part of your app when the token comes back you want to throw and alert for example. 

In traditional OO style architecture that would be no probs you would do something like:

```
class Controller
{
    
    init()
    {
        api("user/token").then(token => store.init({token}));
    }
    
    refreshToken()
    {
        api("user/token")
            .then(token => store.update({token}))
            .then(() => alert("yey token done!"));
    }
    
}
```

When you are initting you would just do controller.init() then when you are in another part of your app and you want a different behaviour you would do controller.refreshToken().

The problem with the callback structure you suggested is that your flow is "fixed" so that this MUST happen then THAT, flow isnt controlled by the calling function. 

I guess you could add more booleans like this:

```
AppStore(({ token }) => {
  // when the token arrives, if we haven't already initialised UserStore, fetch user data
  if (token && !UserStore()) {
    api.get('user/data').then(userData => UserStore.init(userdata))
    else if (token && UserStore().isRefreshing)
    api.get('user/someOtherData').then(data => UserStore.updateData(data))
  }
})
```

But that feels a little nasty to me for some reason.. Perhaps it shouldnt?

Again, apologies if this makes no sense.

Cheers,
Mike

**Comment by jesseskinner** [comment]
Yeah I know what you mean. It feels nasty because you're use modes to switch between different loading behaviour. You can use Hoverboard stores similar as you would promises. Split that out into two different actions that you can call when needed:

export default function init() {
  var unsubscribe = AppStore(({ token }) => {
    if (token && !UserStore()) {
      api.get('user/data').then(userData => UserStore.init(userdata))
      unsubscribe()
    }
  })
}

export default function refreshToken() {
  var unsubscribe = AppStore(({ token }) => {
    if (token) {
      api.get('user/someOtherData').then(data => UserStore.updateData(data))
      unsubscribe()
    }
  })
}
```

**Comment by jesseskinner** [comment]
Or you could wrap a promise around a store -

```javascript
export function refreshToken() {
  return new Promise(resolve => {
    const done = AppStore(({ token }) => {
      if (token) {
        resolve(api.get('user/someOtherData'))
        done()
    }
  })
}

refreshToken().then(data => UserStore.updateData(data))
```

**Comment by mikecann** [comment]
Oh cool, that latter one looks interesting. 

I wasnt aware of the unsubscribe feature, thats good to know. 

Thanks!
