### ISSUE TITLE
mixins for React

### ISSUE THREAD

**Issue by prabirshrestha** [jesseskinner/hoverboard#8]
Any plans to add mixins for React?

Adding these are quite painful.

```js
componentDidMount() {
    this._disposeTodoSubscription = TodoStore.getState(state => this.setState({ todos: state.todos }));
},
componentWillUnmount() {
    this._disposeTodoSubscription();
}
```

Reflux currently has

```js
mixins: [Reflux.connect(todoStore, "todos")]
```

and `Reflux.ListenerMixin`

```js
mixins: [Reflux.ListenerMixin)],
onTodoChange(state) {
    this.setState({ todos: state.todos });
},
componentDidMount() {
    this.listenTo(todoStore, this.onTodoChange);
}
```

**Comment by prabirshrestha** [comment]
Currently here is a mixin I'm using.

```js
let HoverboardListenerMixin = {
    componentWillMount() {
        this._hoverboardSubscriptions = [];
    },
    subscribe(subscription) {
        this._hoverboardSubscriptions.push(subscription);
    },
    componentWillUnmount() {
        this._hoverboardSubscriptions.forEach(unsubscribe => unsubscribe());
        this._hoverboardSubscriptions = [];
    }
};
```

Here is how I use it in a react class.

```js
componentDidMount() {
        this.subscribe(TodoStore.getState(state => this.setState({ todos: state.todos })));
},
```

**Comment by jesseskinner** [comment]
Thanks for the feedback Prabir!

I had considered providing a mixin, I think it's a good idea.

My code uses something like your first example, and yes it can become painfully repetitive. I like how Reflux has two mixins, one as a mixin generator, the other more generic like your HoverboardListenerMixin. I'll try something similar to this.

I don't think I'll include it as part of the standard Hoverboard object, to keep the size of the library down. So I'd rather have them as files in the source that can be included, ie. something like `require('hoverboard/mixins/listener')` instead of `require('hoverboard').ListenerMixin`.

**Comment by prabirshrestha** [comment]
I'm fine with `require('hoverboard/mixins/listener')` as long as we have mixins :)

**Comment by jesseskinner** [comment]
@prabirshrestha What do you think of spinning this off as a separate project/dependency that can be used with any unsubscribe functions? Because it's a good general mixin that could also be used to cleanup/abort `setTimeout` and other things. eg.

```javascript
var timeout = setTimeout(function(){ /* whatever */ }, 60000);

this.subscribe(function() {
   clearTimeout(timeout);
});
```

**Comment by jesseskinner** [comment]
@prabirshrestha 

I've added a mixin utility, similar to `Reflux.connect`, in commit 4366883, version 1.4.0+.

You can use it like this:

```javascript
var InboxStore = require('app/stores/inbox');
var HoverboardMixin = require('hoverboard/src/util/mixin');

var Inbox = React.createClass({
	mixins: [ HoverboardMixin(InboxStore, 'inbox') ],

	render: function() {
		if (this.state && this.state.inbox) {
			// render with this.state.inbox
		}
	}
});
```

Note that the second "key" argument is optional. If you leave it off then the whole state of the store will be passed to the components setState method.

I still think your generic subscribe/unsubscribe mixin is pretty useful and could stand alone as a "react-subscribe-mixin" project, or something like that.

Let me know what you think, thanks!

**Comment by prabirshrestha** [comment]
@jesseskinner I started a discussion in the main reactjs project. https://github.com/facebook/react/issues/3314

**Comment by prabirshrestha** [comment]
@jesseskinner Looks good to me. But not sure if this is a good idea incase you need to add more mixins in the future.

```js
var HoverboardMixin = require('hoverboard/src/util/mixin');
```

**Comment by JakeCoxon** [comment]
I want to throw this idea out there as a possible alternative to using mixins. It's something that I'm using in my code together with Hoverboard.

I create a higher-order component[1] that I can wrap together a store and an inner component. The datastore state is passed to the inner component as props. This separates the component rendering and the data-fetching as 'Container Components'[2] and it means you have the ability to reuse the component with data not from a store (static-data/tests/styleguides).

```
import React from "react";
 
export default Store => ComposedComponent => React.createClass({

    getInitialState() {
        return Store.getState();
    },

    componentDidMount() {
        this.unsubscribe = Store.getState(state => this.setState(state));
    },

    componentWillUnmount() {
        this.unsubscribe();
    },
  
    render() {
        return <ComposedComponent {...this.props} {...this.state} />;
    }

});
```

Usage:

```
import HoverboardComponent from "./hoverboard-component.js"
import Hoverboard from 'hoverboard'

const MyDataStore = Hoverboard({
    getInitialState() {
        setTimeout(() => this.setState({ myData: 123 }), 1000);
        return { myData: 0 };
    }
});

const MyDataStoreWrapper = HoverboardComponent(MyDataStore)

const ViewComponent = React.createClass({
    render() {
        return <div>{this.props.myLabel}: {this.props.myData}</div>
    }
});

...
render() {
  const DataViewComponent = MyDataStoreWrapper(ViewComponent)
  return <DataViewComponent myLabel="something"/>;
}
```

[1] https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775
[2] https://medium.com/@learnreact/container-components-c0e67432e005
[3] https://github.com/acdlite/flummox-immutable-store/blob/master/docs/why-flux-component-is-better-than-flux-mixin.md

**Comment by jesseskinner** [comment]
@JakeCoxon Thanks! Very helpful example.

**Comment by prabirshrestha** [comment]
@jesseskinner could you also include hoverboard.mixin.js and hoverboard.mixin.min.js in the dist folder?

**Comment by jesseskinner** [comment]
@prabirshrestha Sure thing. I'd like to incorporate a wrapper like @JakeCoxon suggested as well, and include both with a better naming scheme to future-proof them as you suggested. util/react-mixin.js maybe?

**Comment by jesseskinner** [comment]
@prabirshrestha This is done, so you can now get the minified mixin from the dist folder.

**WARNING** I moved the source location as you suggested (src/util/react/mixin), so you'll need to update your projects accordingly.
