### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by dzannotti** [jesseskinner/hoverboard#9]
This module does not work with react native, triggers Unexpected end of script. I have no idea what's causing it tho :(

**Comment by dzannotti** [comment]
```
var Hoverboard = (function(){ .... })();
module.exports = Hoverboard;
```
Seems to fix the issue. not sure what's causing it tho

**Comment by jesseskinner** [comment]
@dzannotti Thanks for taking the time to report this. I haven't had the chance to use React Native yet. Are you able to put together a test case to demonstrate the error?

**Comment by dzannotti** [comment]
no need :)
```
npm install hoverboard
```
then just:
```
var Hoverboard = require('hoverboard');
```
triggers a red screen of death which goes away once the above "patch" is applied. Still not sure why

**Comment by jesseskinner** [comment]
Weird, I'll try to figure it out soon, thanks for the details. Hopefully the workaround lets you work around this in the meantime, so to speak :)

**Comment by dzannotti** [comment]
Yup, no rush.
I'm 99% sure it has to do with the way react-native packager works (doesn't like a function being exported rather than an object maybe?)

**Comment by jesseskinner** [comment]
Yeah I'd be interested to figure it out, if you're right then it sounds like it may actually be a bug in react-native.

**Comment by jesseskinner** [comment]
@dzannotti Dumbest thing, it was the // comment at the end of the file. Adding a newline to the file fixed it. I'm guessing it had to do with JavaScript files being concatenated. Thanks again!

**Comment by dzannotti** [comment]
Awesome to know.
I didn't really think about that, because i have "auto add newline at end of file" when i save changes in my editor. But yes probably has to do with the way the files are concatenated by the packager
